project/core/views.py
"""
.. topic:: Core (views)

    Este é o módulo inicial do sistema.

    Apresenta as telas de início, informação e procedimentos de carga de dados em lote.

.. topic:: Funções

    * PegaArquivo: Faz o upload do arquivo desejado

.. topic:: Ações relacionadas aos bolsistas

    * index: Primeiro template chamado na inicialização do sistema. Reprograma agendamentos.
    * inicio: Tela inicial do sistema
    * info: Tela de informações
    * CarregaUnidades: Carrega dados de unidade em lote
    * CarregaPessoas: Carrega dados de pessoa em lote
    * CarregaAtividades: Carrega daddos de atividaes e lote
    * apoio_i: Auxiliar para o menu em cascata de Funções de apoio
    * cargas_i: Auxiliar para o menu em cascata de Carga de dados
    * interno_i: Auxiliar para o menu em cascata de Funções internas

"""

# core/views.py

from flask import render_template,url_for,flash, redirect, request, Blueprint, send_from_directory
from flask_login import current_user, login_required

import os
from datetime import datetime as dt, date
import tempfile
from werkzeug.utils import secure_filename

from datetime import datetime

from project.core.forms import  RefEnvioForm
from project import db, sched
from project.models import users, Log_Auto

from project.usuarios.views import registra_log_auto

from project.envio.views import envia_API


core = Blueprint("core",__name__)



@core.route('/')
def index():
    """
    +---------------------------------------------------------------------------------------+
    |Ações quando o aplicativo é colocado no ar.                                            |
    |Inicia jobs de envio e de reenvio conforme ultimo registro de agendamento no log.      |
    +---------------------------------------------------------------------------------------+
    """

    # pegar unidades de todos os usuários para conferir a existência de jobs de envio para cada uma
    instituicoes = db.session.query(users.instituicaoId).filter(users.instituicaoId != None).all()

    if instituicoes != None:

        instituicoes_lista = [i.instituicaoId for i in instituicoes]
    
        for i in instituicoes_lista:
        
            # pega últimos registros de agendamento no log
            log_agenda_ant_envio = db.session.query(Log_Auto.id, Log_Auto.msg)\
                                            .filter(Log_Auto.msg.like('* Agendamento de envio:'+'%'+str(i)))\
                                            .order_by(Log_Auto.id.desc())\
                                            .first()
            log_agenda_canc_envio = db.session.query(Log_Auto.id, Log_Auto.msg)\
                                                .filter(Log_Auto.msg.like('* Agendamento cancelado.'+'%'+str(i)))\
                                                .order_by(Log_Auto.id.desc())\
                                                .first()

            if log_agenda_ant_envio != None:

                if log_agenda_canc_envio != None and log_agenda_canc_envio.id > log_agenda_ant_envio.id:
                    pass
                
                else:  #não há cancelamento de agendamento

                    # pega dados do último agendamento e se certifica que não há job_envia_planos na memória
                    periodicidade = (log_agenda_ant_envio.msg[24:].split())[0]
                    hora_min      = (log_agenda_ant_envio.msg[24:].split())[2]
                    inst          = i

                    try:
                        job_existente = sched.get_job('job_envia_planos_'+str(inst))
                        if job_existente:
                            executa = False
                        else:
                            executa = True      
                    except:
                        executa = True

                    if executa:  # não achou nada na memória, coloca agenda job_envia_planos_<id da instituição>

                        print ('*** Agendamento inicial: '+ periodicidade + ' - ' + hora_min)

                        id = 'job_envia_planos_'+str(inst)
                        
                        tipo_envio = 'enviar'

                        if hora_min[1] == ':':
                            hora_min = '0'+ hora_min
                        s_hora   = hora_min[0:2]    
                        hora     = int(s_hora)
                        s_minuto = hora_min[3:5]
                        minuto   = int(s_minuto)

                        if periodicidade == 'Diária':
                            msg = ('*** Agendamento inicial de '+id+' como DIÁRIO, rodando de segunda a sexta-feira, às '+s_hora+':'+s_minuto+' ***')
                            print(msg)
                            dia_semana = 'mon-fri'
                            try:
                                sched.add_job(trigger='cron', id=id, func=lambda:envia_API(tipo_envio, inst), day_of_week=dia_semana, hour=hora, minute=minuto, misfire_grace_time=3600, coalesce=True)
                                sched.start()
                            except:
                                sched.reschedule_job(id, trigger='cron', day_of_week=dia_semana, hour=hora, minute=minuto)
                        elif periodicidade == 'Semanal':
                            msg = ('*** Agendamento inicial de '+id+' como SEMANAL, rodando toda sexta-feira, às '+s_hora+':'+s_minuto+' ***')
                            print(msg)
                            dia_semana = 'fri'
                            try:
                                sched.add_job(trigger='cron', id=id, func=lambda:envia_API(tipo_envio, inst), day_of_week=dia_semana, hour=hora, minute=minuto, misfire_grace_time=3600, coalesce=True)  
                                sched.start()
                            except:
                                sched.reschedule_job(id, trigger='cron', day_of_week=dia_semana, hour=hora, minute=minuto)
                        elif periodicidade == 'Mensal':
                            msg = ('*** Agendamento inicial de '+id+' com MENSAL,  rodando na primeira sexta-feira de cada mês, às '+s_hora+':'+s_minuto+' ***')
                            print(msg)
                            dia = '1st fri'
                            try:
                                sched.add_job(trigger='cron', id=id, func=lambda:envia_API(tipo_envio, inst), day=dia, hour=hora, minute=minuto, misfire_grace_time=3600, coalesce=True)
                                sched.start()
                            except:
                                sched.reschedule_job(id, trigger='cron', day=dia, hour=hora, minute=minuto)   

                        # agendanto também o job_envia_planos_novamente, caso necessário
                        log_agenda_ant_reenvio = db.session.query(Log_Auto.id, Log_Auto.msg)\
                                                .filter(Log_Auto.msg.like('* Agendamento de reenvio:'+'%'+str(i)))\
                                                .order_by(Log_Auto.id.desc())\
                                                .first()

                        if log_agenda_ant_reenvio and log_agenda_ant_reenvio.id > log_agenda_ant_envio.id:

                            id='job_envia_planos_novamente_'+str(inst)
                            
                            tipo_envio = 'reenviar'

                            hora += 1
                            s_hora = str(hora)
                            # minuto += 2
                            # s_minuto = str(minuto)
                                
                            if periodicidade == 'Diária':
                                msg = ('*** Agendamento inicial de '+id+' como DIÁRIO, rodando de segunda a sexta-feira, às '+s_hora+':'+s_minuto+' ***')
                                print(msg)
                                dia_semana = 'mon-fri'
                                try:
                                    sched.add_job(trigger='cron', id=id, func=lambda:envia_API(tipo_envio, inst), day_of_week=dia_semana, hour=hora, minute=minuto, misfire_grace_time=3600, coalesce=True)
                                except:   
                                    sched.reschedule_job(id, trigger='cron', day_of_week=dia_semana, hour=hora, minute=minuto)
                            elif periodicidade == 'Semanal':
                                msg =  ('*** Agendamento inicial de '+id+' como SEMANAL, rodando toda sexta-feira, às '+s_hora+':'+s_minuto+' ***')
                                print(msg)
                                dia_semana = 'fri'
                                try:
                                    sched.add_job(trigger='cron', id=id, func=lambda:envia_API(tipo_envio, inst), day_of_week=dia_semana, hour=hora, minute=minuto, misfire_grace_time=3600, coalesce=True)  
                                except:  
                                    sched.reschedule_job(id, trigger='cron', day_of_week=dia_semana, hour=hora, minute=minuto)    
                            elif periodicidade == 'Mensal':
                                msg =  ('*** Agendamento inicial de '+id+' como MENSAL, rodando na primeira sexta-feira de cada mês, às '+s_hora+':'+s_minuto+' ***')
                                print(msg)
                                dia = '1st fri'
                                try:
                                    sched.add_job(trigger='cron', id=id, func=lambda:envia_API(tipo_envio, inst), day=dia, hour=hora, minute=minuto, misfire_grace_time=3600, coalesce=True)
                                except:
                                    sched.reschedule_job(id, trigger='cron', day=dia, hour=hora, minute=minuto)

    
    return render_template ('index.html')



@core.route('/inicio')
def inicio():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta a tela inicial do aplicativo.                                                |

project/templates/apoio.html
{% extends "template_gov.html" %}
{% block content %}

  <div class="col mb-5">
    <div class="br-breadcrumb">
      <ul class="crumb-list">
        <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
        <!-- <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior</a></li>
        <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior2</a></li>
        <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior3</a></li>
        <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior4</a></li> -->
        <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Funções de apoio</span>
        </li>
      </ul>
    </div>
  </div>


  {% if current_user.is_authenticated and current_user.userAtivo %} 
  <div class="row mt-5">
    <div class="d-flex justify-content-center  flex-wrap">

      {% with 
        icon="fa-network-wired", 
        title="Unidades",
        description="Lista das unidades da instituição, com as opções de inclusão, alteração e filtro. Pode-se também selecionar entre ativas e inativas.",
        link=url_for("unidades.lista_unidades",lista="ativas")
      %}
        {% include "card_menu.html" %}
      {% endwith %}

      {% with 
        icon="fa-users", 
        title="Pessoas",
        description="Lista das pessoas da instituição, com as opções de inclusão, alteração e filtro. Há destaque para a informação de gestores do sistema.",
        link=url_for("pessoas.lista_pessoas")
      %}
        {% include "card_menu.html" %}
      {% endwith %}


      {% with 
        icon="fa-pen", 
        title="Atividades",
        description="Lista das atividades da instituição, com as opções de inclusão e alteração. Pode-se também selecionar entre válidas e não válidas.",
        link=url_for("atividades.lista_atividades",lista="ativas")
      %}
        {% include "card_menu.html" %}
      {% endwith %}


      {% with 
        icon="fa-eye", 
        title="Dados Auxiliares",
        description="Consulta e atualização de tabelas operacionais do SISGP.",
        link=url_for("padroes.padroes_i")
      %}
        {% include "card_menu.html" %}
      {% endwith %}

      {% with 
        icon="fa-list", 
        title="Consultas",
        description="Consultas de interesse à gestão do PGD da instituição.",
        link=url_for("consultas.consultas_i")
      %}
        {% include "card_menu.html" %}
      {% endwith %}

      {% with 
        icon="fa-upload", 
        title="Carga de dados",
        description="Inserção ou atualização em lote de Unidades, Pessoas ou Atividades.",
        link=url_for("core.cargas_i")
      %}
        {% include "card_menu.html" %}
      {% endwith %}


    </div>
  </div>
  {% endif %}


{% endblock %}

project/templates/card_menu.html
<div class="card mx-3 mb-3 flex-fill col-md-3">
  <div class="card-body text-center card-box position-relative">
    <a href="{{link}}">
      <i class="fa-solid {{icon}}"></i>
      <h5 class="card-title mt-3">{{title}}</h5>
    </a>
    <button tabindex="0" class="btn rounded-circle btn-help" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-title="{{title}}" data-bs-content="{{description}}"><i class="fa-solid fa-info"></i></button>
  </div>
</div>

project/templates/email.html
{% extends "template_gov.html" %}
{% block content %}
<div class="container">

<div class="jumbotron">

  {% macro render_field(field,obr) %}
    {% if obr == True %}
      <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
    {% else %}
      <dt>{{ field.label(class="form-control-label") }}
    {% endif %}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class=errors>
      {% for error in field.errors %}
        <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  {% endmacro %}

<form method="POST">

  {{form.hidden_tag()}}

  <div class="form-group">
    {{render_field(form.email,class="form-control", placeholder="Insira seu e_mail",obr=True)}}
  </div>

  {{form.submit(class="br-button secondary mr-3")}}

</form>

</div>
</div>
{% endblock %}

project/templates/email_confirmation.html
  Sua conta foi criada no ApoioSisgp com sucesso!
  <br>
  Por favor, utilize o link abaixo para confirmar seu endereço de e-mail.
  <br>
  ** ATENÇÃO: O link tem validade de uma hora! **
  <br>

  <a href="{{ confirm_url }}">{{ confirm_url }}</a>

  --

project/templates/info.html
{% extends "template_gov.html" %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <h3>O Módulo de Envio para o PGD CADE</h3>
    <p></p>
    <p>Baseado no MEAG SISGP, este sistema oferece somente a parte de envio de dados.</p>
    

  </div>
</div>



{% endblock %}

project/templates/interno.html
{% extends "template_gov.html" %}
{% block content %}

  <div class="col mb-5">
    <div class="br-breadcrumb">
      <ul class="crumb-list">
        <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
        <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Funções internas</span>
        </li>
      </ul>
    </div>
  </div>

  {% if current_user.is_authenticated and current_user.userAtivo %} 
    <div class="row mt-5">
      <div class="d-flex justify-content-center  flex-wrap">
        
        {% with 
          icon="fa-book", 
          title="Diário",
          description="Registro das principais ações realizadas no sistema. A tela inicial mostra as últimas 24 horas de
          atividades, mas há opção de filtro para um período maior.",
          link=url_for("usuarios.log",tipo="geral")
        %}
          {% include "card_menu.html" %}
        {% endwith %}

        {% with 
          icon="fa-user", 
          title="Gestão de usuários",
          description="Lista dos usuários registrados no sistema com a opção de ativação de usuário recém registrado, bem 
          como a permição de uso da funcionalidade de envio de dados .",
          link=url_for("usuarios.view_users")
        %}
          {% include "card_menu.html" %}
        {% endwith %}

        {% with 
          icon="fa-lock", 
          title="Trocar senha",
          description="Formulário onde o usuário logado pode trocar sua senha.",
          link=url_for("usuarios.troca_senha")
        %}
          {% include "card_menu.html" %}
        {% endwith %}

        

      </div>
    </div>

  {% endif %}


{% endblock %}

project/templates/login.html
{% extends "template_gov.html" %}
{% block content %}



  {% macro render_field(field,obr) %}
    {% if obr == True %}
      <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
    {% else %}
      <dt>{{ field.label(class="form-control-label") }}
    {% endif %}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class=errors>
      {% for error in field.errors %}
        <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  {% endmacro %}

<form method="POST">

  {{form.hidden_tag()}}

  <div class="row">

    <div class="col-sm">
      <fieldset>
        <legend>Dados para acesso</legend>
        <div class="row">
          <div class="col-4">
            <div class="br-input">
              {{render_field(form.email,class="form-control", placeholder="Insira seu e_mail",obr=True)}}
            </div>
          </div>
        </div>  
        <div class="row">  
          <div class="col-4">
            <div class="br-input input-button">
              {{render_field(form.password,class="form-control", placeholder="Senha",obr=True)}}
            </div>
          </div>
        </div>
        {{form.submit(class="br-button primary small")}}

        <div class="form-group">
          <p><br><a class="" href="{{url_for('usuarios.reset')}}">Esqueceu, ou quer trocar sua senha? Clique aqui.</a></p>
        </div>
      </fieldset>
    </div>


  </div>


  <!-- <div class="form-group">
    <div class = "col-5">
      {{render_field(form.email,class="form-control", placeholder="Insira seu e_mail",obr=True)}}
    </div>
  </div>

  <div class="form-group">
    <div class = "col-5">
      {{render_field(form.password,class="form-control", placeholder="Senha",obr=True)}}
    </div>
  </div> -->

 

</form>


{% endblock %}

project/templates/registra_ref_envios.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('core.interno_i')}}">Funções Internas</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Data de referência para envios</span>
      </li>
    </ul>
  </div>
</div>

<div class="container">

<div class="jumbotron">

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form method="POST">
  {{form.hidden_tag()}}

  <div class="form-group col-3">
    {{render_field(form.data_ref,class="form-control",obr=True)}}
  </div>


  <br>

    {{form.submit(class="br-button secondary mr-3")}}

</form>

</div>
</div>
{% endblock %}

project/templates/update_user.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('core.interno_i')}}">Funções Internas</a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('usuarios.view_users')}}">Usuários</a></li>
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Troca senha</span>
      </li>
    </ul>
  </div>
</div>

<div class="container">

<div class="jumbotron">
<h3>Alterar situação do usuário {{ name }}</h3>

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form class="needs-validation" method='POST' >
  {{ form.hidden_tag() }}
  
<br>

<div class="row">

  <div class="col-6">

    <div class="form-group col-6">
      {{ render_field(form.ativo, obr=True) }}
    </div>

    <div class="form-group col-8">
      {{ render_field(form.unidade, obr=True) }}
    </div>

  </div>
  
  <div class="col-6">

    <div class="form-group col-8">
      {{ render_field(form.envia, obr=True) }}
    </div>

    <div class="form-group col-10">
      {{ render_field(form.user_api, obr=False) }}
    </div>  
    
    <div class="form-group col-6">
      {{ render_field(form.senha_api, obr=False) }}
    </div>

  </div>

</div>

<div class="row justify-content-center">
  <br>
  <div class="col-2">
    {{ form.submit(class="br-button secondary mr-3") }}
  </div>
  <div class="col-2"></div>
</div>  

</div>
</div>

{% endblock %}

project/templates/user_log.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      {% if tipo == 'geral' %}
       <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('core.interno_i')}}">Funções Internas</a></li>
       <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Diário</span>
      {% elif tipo == 'envio' %}
        <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('envio.envio_i')}}">Envio</a></li>
        <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Diário de envios</span>
      {% endif %}
      </li>
    </ul>
  </div>
</div>

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}
<form class="form-group" method='POST'>
  {{ form.hidden_tag() }}

  <div class="form-group row align-items-center">

    <div class="form-group col-4">
      {{ render_field(form.data_ini,class="form-control",placeholder="dd/mm/aaaa",obr=False) }}
    </div>
    <div class="form-group col-4">
      {{ render_field(form.data_fim,class="form-control",placeholder="dd/mm/aaaa",obr=False) }}
    </div>
    <div class="form-group col-2">
      {{ form.submit(class="br-button secondary mr-3") }}
    </div>

  </div>    
</form> 
<div class="card">
  <div class="card-header">
    <div class="d-flex flex-column flex-md-row justify-content-between">
      {% if tipo == 'geral' %}
        <h5 class="header-list">Diário</h5>
      {% elif tipo == 'envio' %}
        <h5 class="header-list">Diário de Envios</h5>
      {% endif %}
      <div class="d-flex justify-content-around">
        
      </div>
    </div>
  </div>
  <div class="card-body">
    <p>(Observação: Se não informadas datas na procura, são apresentados registros das <b>últimas 24 horas</b>)</p>

    

    {% if log == None %}
      <h3>Nada, por enquanto.</h3>

    {% else %}
      <table class="table table-striped table-hover table-sm">
        <thead>
          <tr>
            <th scope="col"><p align = "center">#</p></th>
            <th scope="col"><p align = "center">Data e Hora</p></th>
            <th scope="col"><p align = "left">Responsável</p></th>
            <th scope="col"><p align = "left">Descrição</p></th>
          </tr>
        </thead>

        <tbody>

          {% for l in log %}

          <tr>
            <th scope="row"><p align = "center"><small>{{l.id}}</small></p></th>
            <td><p align = "center"><small> {{l.data_hora.strftime("%x - %H:%M")}} </small> </p></td>
            <td><p align = "left"><small> {{l.userNome}} </small></p></td>
            <td><p align = "left"><small>{{l.msg}}</small></p></td>
          </tr>

          {% endfor %}

        </tbody>

      </table>
    {% endif %}
  </div>
</div>

{% endblock %}

project/templates/view_users.html
{% extends "template_gov.html" %}
{% block content %}

<div class="col mb-5">
  <div class="br-breadcrumb">
    <ul class="crumb-list">
      <li class="crumb home"><a class="br-button circle" href="{{url_for('core.inicio')}}"><span class="sr-only">Página inicial</span><i class="fa fa-home"></i></a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="{{url_for('core.interno_i')}}">Funções Internas</a></li>
      <!-- <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior2</a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior3</a></li>
      <li class="crumb"><i class="icon fa fa-chevron-right"></i><a href="javascript:void(0)">Tela Anterior4</a></li> -->
      <li class="crumb" data-active="active"><i class="icon fa fa-chevron-right"></i><span>Usuários</span>
      </li>
    </ul>
  </div>
</div>


<div class="card">
  <div class="card-header">
    <div class="d-flex flex-column flex-md-row justify-content-between">
      <h5 class="header-list">Lista dos usuários</h5>
      <div class="d-flex justify-content-around">
      </div>
    </div>
  </div>
  <div class="card-body">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>ID</th>
          <th>Usuário</th>
          <th>E-mail</th>
          <th align="center">Data reg.</th>
          <th align="center">E-mail conf.?</th>
          <th align="center">E-mail conf. em</th>
          <th align="center">Último login</th>
          <th align="center">Ativo?</th>
          <th align="center">Envia PT?</th>
          </tr>
      </thead>
      <tbody>
        {% for user in lista %}
          <tr>
            <td> <a href="{{url_for('usuarios.update_user', user_id=user.id)}}"><abbr title="Clique aqui atualizar">{{ user.id }} </td>
            <td> {{ user.userNome }} </td>
            <td> {{ user.userEmail }} </td>
            <td align="center"> {% if user.registered_on != None %} {{user.registered_on.strftime('%d/%m/%Y')}} {% endif %} </td>
            <td align="center"> {% if user.email_confirmed == True %} Sim {% else %} Não {% endif %} </td>
            <td align="center"> {% if user.email_confirmed_on != None %} 
                                  {{user.email_confirmed_on.strftime('%d/%m/%Y')}}
                                {% else %}
                                  <a href="{{url_for('usuarios.confirm', userId=user.id)}}"><abbr title="Clique aqui enviar novo e-mail de confirmação.">Enviar e-mail</abbr> 
                                {% endif %}
            </td>
            <td align="center"> {% if user.current_logged_in != None %} {{user.current_logged_in.strftime('%d/%m/%Y')}} {% endif %}</td>
            <td align="center"> {% if user.userAtivo == True %} Sim {% else %} Não {% endif %} </td>
            <td align="center"> {% if user.userEnvia == True %} Sim {% else %} Não {% endif %} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}